api:
  api-prefix: /api/v1
  strip-prefix: 2

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${api.api-prefix}/identity/**
          filters:
            - StripPrefix=${api.strip-prefix}
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${api.api-prefix}/profile/**
          filters:
            - StripPrefix=${api.strip-prefix}
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${api.api-prefix}/notification/**
          filters:
            - StripPrefix=${api.strip-prefix}
        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=${api.api-prefix}/post/**
          filters:
            - StripPrefix=${api.strip-prefix}
        - id: file-service
          uri: http://localhost:8084
          predicates:
            - Path=${api.api-prefix}/file/**
          filters:
            - StripPrefix=${api.strip-prefix}
        - id: chat-service
          uri: http://localhost:8085
          predicates:
            - Path=${api.api-prefix}/chat/**
          filters:
            - StripPrefix=${api.strip-prefix}

server:
  port: 8888