spring:
  application:
    name: profile-service
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8081
  servlet:
    context-path: /profile

app:
  service:
    url: ${FILE_SERVICE_URL}
