spring:
  application:
    name: profile-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: minhkha1606
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8081
  servlet:
    context-path: /profile

app:
  service:
    url: http://localhost:8084/file
