spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
server:
  port: 8085
  servlet:
    context-path: /chat

app:
  profile:
    url: ${PROFILE_SERVICE_URL}
  identity:
    url: ${IDENTITY_SERVICE_URL}